[workspace]
members = [
    "crates/amc-core",
    "crates/amc-cli",
    "applications/amc",
    "applications/amc-todo",
]

[profile.release]
debug = true

[patch.crates-io]
stateright = { git = "https://github.com/stateright/stateright", branch = "master" }
