[workspace]
members = [
    "amc-core",
    "amc",
    "amc-cli",
    "amc-todo",
]

[profile.release]
debug = true

[patch.crates-io]
stateright = { git = "https://github.com/stateright/stateright", branch = "master" }
