[package]
name = "amc-core"
version = "0.1.0"
edition = "2021"

[dependencies]
stateright = "0.29.0"
automerge = "0.2.0"
clap = { version = "4.1.1", features = ["derive"] }
num-format = { version = "0.4.4", features = ["with-system-locale"] }

[dev-dependencies]
num_cpus = "1.15.0"
