[package]
name = "amc-automerge"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
automerge = "0.2.0"
clap = { version = "4.1.1", features = ["derive"] }
stateright = "0.29.0"
amc = { path = "../../crates/amc" }
