[package]
name = "amc"
version = "0.1.0"
edition = "2021"

[dependencies]
automerge = "0.1.0"
clap = { version = "3.1.18", features = ["derive"] }
num_cpus = "1.13.1"
stateright = "0.29.0"
amc-core = { path = "../amc-core" }
amc-cli = { path = "../amc-cli" }
