name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v12
        with:
          name: automerge-model-checking
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix build -L .#amc-docs

      - run: |
          mkdir built-docs/
          cp -r result/target/doc built-docs/.

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: built-docs/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

