name: "Docs"

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # docs will get overwritten anyway so just don't bother
  cancel-in-progress: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v18
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: cachix/cachix-action@v12
      with:
        name: automerge-model-checking
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - run: nix build -L .#amc-docs

    - run: |
        set -x

        git pull origin gh-pages --ff
        git checkout gh-pages

        rm -rf *

        cp -r result/target/doc doc/

        git add .
        git commit -m "Updating docs"
        git push origin gh-pages
